Adds dockerized test suite.
klpx/akka-stream-postgresql-copy pull request #4
Opened 2020-05-15 15:35 UTC by jrouly

Includes my Scala 2.13 PR but also adds dockerized postgres container tests.

This way multiple versions of Postgres can be tested during the same test suite execution.

2020-05-15 15:52 UTC, jrouly commented
There's no CI for this repo, but tests pass on my local machine with no issues.

2020-05-15 19:44 UTC, klpx commented
Thank you a lot for the contriubution! Don't you mind if i'll merge #3, then I'll set up Actions CI (instead of Travis that is not working for some reason, and I want to test this new Actions :) ) and we merge this separately from 2.13 support?

2020-05-15 20:18 UTC, jonhlee approved these changes

2020-05-15 20:22 UTC, jrouly commented
@klpx absolutely, sounds like a good plan. I'll go ahead and rebase.

2020-05-15 20:25 UTC, jrouly commented
I think my most recent commit introduced a deadlock, tests are no longer terminating locally. Going to mark this Do Not Merge until I get that resolved.

2020-05-15 22:24 UTC, Q69K commented
CI is ready in master as well.

2020-05-15 22:53 UTC, jrouly commented
I fixed the issue where the tests would just hang if containers failed to start. However tests are pretty slow (as each test starts up 4 versions of postgres). Lots of room for improvement.

I've got some local code to add container caching (sharing containers between tests) that I might push up in another PR, but I think [testcontainers](https://www.testcontainers.org/) might be a better solution than my `mutable.Map` of containers :)

2020-05-16 17:06 UTC, Q69K commented
I run this locally and it's failing if an image is not pulled beforehand.
I see there is some code to pull image, but looks like it's not enough
```
akka-streams-postgresql-copy$ sbt "++2.11.12 test:testOnly it.CopySinkSpec"
[info] Loading settings for project global-plugins from build.sbt,gpg.sbt ...
[info] Loading global plugins from /home/alex/.sbt/1.0/plugins
[info] Loading settings for project akka-streams-postgresql-copy-build from plugins.sbt ...
[info] Loading project definition from /home/alex/ss/stackvista/akka-streams-postgresql-copy/project
[info] Loading settings for project akka-streams-postgresql-copy from build.sbt,sonatype.sbt ...
[info] Set current project to akka-streams-postgresql-copy (in build file:/home/alex/ss/stackvista/akka-streams-postgresql-copy/)
[info] Setting Scala version to 2.11.12 on 1 projects.
[info] Reapplying settings...
[info] Set current project to akka-streams-postgresql-copy (in build file:/home/alex/ss/stackvista/akka-streams-postgresql-copy/)
[info] Compiling 3 Scala sources to /home/alex/ss/stackvista/akka-streams-postgresql-copy/target/scala-2.11/test-classes ...
[warn] there was one deprecation warning; re-run with -deprecation for details
[warn] one warning found
[info] Compiling 3 Scala sources to /home/alex/ss/stackvista/akka-streams-postgresql-copy/target/scala-2.11/test-classes ...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] CopySinkSpec:
[info] PgCopySink
[info] - should copy simple stream with one element *** FAILED ***
[info]   com.github.dockerjava.api.exception.NotFoundException: No such image: postgres:12-alpine
[info]   at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:66)
[info]   at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:171)
[info]   at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:159)
[info]   at org.glassfish.jersey.process.internal.Stages.process(Stages.java:147)
[info]   at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:301)
[info]   at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:609)
[info]   at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
[info]   at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
[info]   at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
[info]   at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
[info]   ...
[info] - should copy simple Seq of tuples *** FAILED ***
[info]   com.github.dockerjava.api.exception.NotFoundException: No such image: postgres:12-alpine
[info]   at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:66)
[info]   at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:171)
[info]   at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:159)
[info]   at org.glassfish.jersey.process.internal.Stages.process(Stages.java:147)
[info]   at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:301)
[info]   at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:609)
[info]   at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
[info]   at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
[info]   at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
[info]   at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
[info]   ...
[info] - should encode special characters correctly *** FAILED ***
[info]   com.github.dockerjava.api.exception.NotFoundException: No such image: postgres:12-alpine
[info]   at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:66)
[info]   at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:171)
[info]   at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:159)
[info]   at org.glassfish.jersey.process.internal.Stages.process(Stages.java:147)
[info]   at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:301)
[info]   at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:609)
[info]   at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
[info]   at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
[info]   at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
[info]   at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
[info]   ...
[info] Run completed in 28 seconds, 66 milliseconds.
[info] Total number of tests run: 3
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 3, canceled 0, ignored 0, pending 0
[info] *** 3 TESTS FAILED ***
[error] Failed tests:
[error]         it.CopySinkSpec
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 38 s, completed May 16, 2020 6:40:30 PM

```

2020-05-16 17:14 UTC, Q69K requested changes

2020-05-16 17:14 UTC, Q69K commented on src/test/scala/util/PostgresFixture.scala
> -  private val password = config.getString("password")
If config is not taken into account anymore, could you drop it then, please? (I mean the whole `application.conf` file)

2020-05-16 17:14 UTC, Q69K commented on src/test/scala/util/PostgresFixture.scala
> +    Future.traverse(PostgresFixture.PostgresImages) { image =>
:+1:

2020-05-16 17:14 UTC, Q69K commented on src/test/scala/util/PostgresFixture.scala
> +        testCode(connection)
This may be helpful for debug
```suggestion
        withClue(s"postgres image: $image") {
          testCode(connection)
        }
```

2020-05-16 19:35 UTC, jrouly commented
> I run this locally and it's failing if an image is not pulled beforehand.
> I see there is some code to pull image, but looks like it's not enough

Just switched to a machine without any existing docker images on it and I'm seeing the same. Looking into it.

2020-05-16 20:27 UTC, jrouly commented
@Q69K Two issues, I was ignoring `pullContainer` failures and there was a `NullPointerException` in `pullContainer` with `docker-java` interop. Should be addressed, but please verify if you could.

```
[akka-streams-postgresql-copy docker]$ sbt "++2.11.12 test:test"
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on
[info] Loading settings for project global-plugins from idea.sbt,plugins.sbt ...
[info] Loading global plugins from /home/jrouly/.sbt/1.0/plugins
[info] Loading settings for project akka-streams-postgresql-copy-build from metals.sbt,plugins.sbt ...
[info] Loading project definition from /data/code/opensource/akka-streams-postgresql-copy/project
[info] Loading settings for project akka-streams-postgresql-copy from build.sbt,sonatype.sbt ...
[info] Set current project to akka-streams-postgresql-copy (in build file:/data/code/opensource/akka-streams-postgresql-copy/)
[info] Setting Scala version to 2.11.12 on 1 projects.
[info] Reapplying settings...
[info] Set current project to akka-streams-postgresql-copy (in build file:/data/code/opensource/akka-streams-postgresql-copy/)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] HealthcheckSpec:
[info] withPostgresConnection
[info] - should provide working connection
[info] CopySinkSpec:
[info] PgCopySink
[info] - should copy simple stream with one element
[info] - should copy simple Seq of tuples
[info] - should encode special characters correctly
[info] CopySourceSpec:
[info] PgCopySource
[info] - should copy bytes as expected
[info] PgCopySource
[info] - should copy lines as expected
[info] Run completed in 44 seconds, 826 milliseconds.
[info] Total number of tests run: 12
[info] Suites: completed 5, aborted 0
[info] Tests: succeeded 12, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 46 s, completed May 16, 2020 3:26:54 PM
```

2020-05-18 10:34 UTC, Q69K requested changes

2020-05-18 10:34 UTC, Q69K commented on src/test/scala/util/Docker.scala
> +      .flatMap(_.getRepoTags.toList)
Here are all images in a system traversed. Some of them can have no tags (normal situation when you build docker images locally). I found that in this case `getRepoTags` returns null. Should be wrapped like this:
```suggestion
    val images: List[String] =
      docker.listImagesCmd()
        .exec().asScala.toList
        .flatMap { x =>
          Option(x.getRepoTags).map(_.toList).getOrElse(Nil)
        }
```

2020-05-18 14:50 UTC, Q69K approved these changes

2020-05-18 14:51 UTC, merged

2020-05-18 14:52 UTC, Q69K commented
:tada: thank you, man!

2020-05-18 15:08 UTC, jrouly commented
Absolutely, thanks for the review and testing!